In [7]:
from keras.models import Sequential
from keras.layers import Dense
#tell about what is Sequestial 
#Sequential?

In [10]:
model = Sequential([
    Dense(32, activation="relu", input_shape=(784,)),
    Dense(10, activation="softmax"),
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                25120     
_________________________________________________________________
dense_1 (Dense)              (None, 10)                330       
Total params: 25,450
Trainable params: 25,450
Non-trainable params: 0
_________________________________________________________________


In [11]:
#Another way to create a sequential NN 
model = Sequential()
model.add(Dense(32, activation = 'relu', input_shape=(784,)))
model.add(Dense(10, activation='softmax'))
model.summary()


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 32)                25120     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                330       
Total params: 25,450
Trainable params: 25,450
Non-trainable params: 0
_________________________________________________________________


#lets learn (layer) activation functions in keras

https://keras.io/api/layers/activations/


# relu function

#tf.keras.activations.relu(x, alpha=0.0, max_value=None, threshold=0)

Applies the rectified linear unit activation function.

With default values, this returns the standard ReLU activation: max(x, 0), the element-wise maximum of 0 and the input tensor.

Modifying default parameters allows you to use non-zero thresholds, change the max value of the activation, and to use a non-zero multiple of the input for values below the threshold.

For example:

>>> foo = tf.constant([-10, -5, 0.0, 5, 10], dtype = tf.float32)
>>> tf.keras.activations.relu(foo).numpy()
array([ 0.,  0.,  0.,  5., 10.], dtype=float32)


>>> tf.keras.activations.relu(foo, alpha=0.5).numpy()
array([-5. , -2.5,  0. ,  5. , 10. ], dtype=float32)


>>> tf.keras.activations.relu(foo, max_value=5).numpy()
array([0., 0., 0., 5., 5.], dtype=float32)


>>> tf.keras.activations.relu(foo, threshold=5).numpy()
array([-0., -0.,  0.,  0., 10.], dtype=float32)



# sigmoid
tf.keras.activations.sigmoid(x)

Sigmoid activation function, sigmoid(x) = 1 / (1 + exp(-x)).

Applies the sigmoid activation function. For small values (<-5), sigmoid returns a value close to zero, and for large values (>5) the result of the function gets close to 1.

Sigmoid is equivalent to a 2-element Softmax, where the second element is assumed to be zero. 
* The sigmoid function always returns a value between 0 and 1

For example:

>>> a = tf.constant([-20, -1.0, 0.0, 1.0, 20], dtype = tf.float32)
>>> b = tf.keras.activations.sigmoid(a)
>>> b.numpy()
array([2.0611537e-09, 2.6894143e-01, 5.0000000e-01, 7.3105860e-01,
         1.0000000e+00], dtype=float32)

Arguments

    x: Input tensor.

Returns

Tensor with the sigmoid activation: 1 / (1 + exp(-x))

# softmax function

tf.keras.activations.softmax(x, axis=-1)

Softmax converts a real vector to a vector of categorical probabilities.

The elements of the output vector are in range (0, 1) and sum to 1.

Each vector is handled independently. The axis argument sets which axis of the input the function is applied along.

Softmax is often used as the activation for the last layer of a classification network because the result could be interpreted as a probability distribution.

The softmax of each vector x is computed as exp(x) / tf.reduce_sum(exp(x)).

The input values in are the log-odds of the resulting probability.

Arguments

    x : Input tensor.
    axis: Integer, axis along which the softmax normalization is applied.

Returns

Tensor, output of softmax transformation (all values are non-negative and sum to 1).

Raises

    ValueError: In case dim(x) == 1.


# tanh function

tf.keras.activations.tanh(x)

Hyperbolic tangent activation function.

For example:

>>> a = tf.constant([-3.0,-1.0, 0.0,1.0,3.0], dtype = tf.float32)
>>> b = tf.keras.activations.tanh(a)
>>> b.numpy()
array([-0.9950547, -0.7615942,  0.,  0.7615942,  0.9950547], dtype=float32)

Arguments

    x: Input tensor.

Returns

Tensor of same shape and dtype of input x, with tanh activation: tanh(x) = sinh(x)/cosh(x) = ((exp(x) - exp(-x))/(exp(x) + exp(-x))).

# exponential function

tf.keras.activations.exponential(x)

Exponential activation function.

For example:

>>> a = tf.constant([-3.0,-1.0, 0.0,1.0,3.0], dtype = tf.float32)
>>> b = tf.keras.activations.exponential(a)
>>> b.numpy()
array([0.04978707,  0.36787945,  1.,  2.7182817 , 20.085537], dtype=float32)

Arguments

    x: Input tensor.

Returns

Tensor with exponential activation: exp(x).

# some more.

Refer: https://keras.io/api/layers/activations/


# Next


* Dense(32, activation="relu", input_shape=(784,)),
input = (784,) dimn, oupt - 32 dimn

# We've done with our model creation and next is compilation of model 

For compilation step, three arguments are required/helpful
 * An optimizer - Its is lesarning technique
 * A loss function - objective to minimize loss
 * A list of matrix - for accuracy etc

In [25]:
#For a multi-class classification problem 
model.compile(optimizer = 'rmsprop',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])

#For a binary classification problems
model.compile(optimizer='rmsprop',
             loss='binary_crossentropy',
             metrics=['accuracy'])

#For a mean squared error regression problem 
model.compile(optimizer='rmsprop',
             loss='mae')

#For custom matrics
import keras.backend as K
def mean_pred(y_true, y_pred):
    return K.mean(y_pred)
model.compile(optimizer='rmsprop',
              loss='binarycrossentropy',
              metrics=['accuracy', mean_pred])


# Lets learn Optimizers 
An optimizer is one of the two arguments required for compiling a Keras model:
    
model.compile(loss='mean_squared_error', optimizer=sgd)

# SGD
keras.optimizers.SGD(lr=0.01, momentum=0., decay=0., nesterov=False)
Arguments:

lr: float >= 0. Learning rate.
momentum: float >= 0. Parameter updates momentum.
decay: float >= 0. Learning rate decay over each update.
nesterov: boolean. Whether to apply Nesterov momentum.
tf.keras.optimizers.SGD(
    learning_rate=0.01, momentum=0.0, nesterov=False, name="SGD", **kwargs
)

Gradient descent (with momentum) optimizer.

Update rule for parameter w with gradient g when momentum is 0:

w = w - learning_rate * g

Update rule when momentum is larger than 0:

velocity = momentum * velocity - learning_rate * g

w = w + velocity

When nesterov=False, this rule becomes:

velocity = momentum * velocity - learning_rate * g

w = w + momentum * velocity - learning_rate * g




# Adagrad
keras.optimizers.Adagrad(lr=0.01, epsilon=1e-6)
It is recommended to leave the parameters of this optimizer at their default values.

Arguments:

lr: float >= 0. Learning rate.
epsilon: float >= 0.

# RMSprop
 

# Adam
Adam class
tf.keras.optimizers.Adam(
    learning_rate=0.001,
    beta_1=0.9,
    beta_2=0.999,
    epsilon=1e-07,
    amsgrad=False,
    name="Adam",
    **kwargs
)
Optimizer that implements the Adam algorithm.

Adam optimization is a stochastic gradient descent method that is based on adaptive estimation of first-order and second-order moments.

According to Kingma et al., 2014, the method is "computationally efficient, has little memory requirement, invariant to diagonal rescaling of gradients, and is well suited for problems that are large in terms of data/parameters".

Some more refer here: https://keras.io/api/optimizers/

# Lets dig on loss 

# Training 

In [39]:
model = Sequential()
model.add(Dense(32,activation='relu', input_dim=100))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='rmsprop',
             loss='binary_crossentropy',
             metrics=['accuracy'])
#Generate dummy data
import numpy as np
data = np.random.random((1000,100))
labels = np.random.randint(2, size=(1000,1))
#model.fit?

In [40]:
model.fit(
        data,
        labels,
        batch_size=32,
        epochs=10, verbose=2,
        callbacks=None,
        validation_data=None,
        shuffle = True,
        class_weight=None,
        sample_weight=None,
        initial_epoch=0)
          

Epoch 1/10
32/32 - 0s - loss: 0.7072 - accuracy: 0.4730
Epoch 2/10
32/32 - 0s - loss: 0.6953 - accuracy: 0.5200
Epoch 3/10
32/32 - 0s - loss: 0.6887 - accuracy: 0.5510
Epoch 4/10
32/32 - 0s - loss: 0.6858 - accuracy: 0.5340
Epoch 5/10
32/32 - 0s - loss: 0.6823 - accuracy: 0.5530
Epoch 6/10
32/32 - 0s - loss: 0.6791 - accuracy: 0.5710
Epoch 7/10
32/32 - 0s - loss: 0.6764 - accuracy: 0.5720
Epoch 8/10
32/32 - 0s - loss: 0.6744 - accuracy: 0.5830
Epoch 9/10
32/32 - 0s - loss: 0.6701 - accuracy: 0.5830
Epoch 10/10
32/32 - 0s - loss: 0.6672 - accuracy: 0.6140


In [43]:
#Runs a single gradient update on a single batch of data.
model.train_on_batch(
                    data[:32],
                    labels[:32],
                    class_weight=None,
                    sample_weight=None,)

[0.6667970418930054, 0.6153100728988647]

In [44]:
def data_gen():
    for datus, label in zip(data, labels):
        yield datus[None,:], label

In [50]:
#train on generator 
model.fit_generator(
                data_gen(),
                steps_per_epoch=5, #900
                epochs=1,
                verbose=1,
                callbacks=None,
                validation_data=None, #this can be a generator or a dataset
                validation_steps=None,
                class_weight=None,
                #max_q_size=10,
                workers=1,
                #pickle_safe=False,
                initial_epoch=0)
                

5/5 [==============================] - 0s 1ms/step - loss: 0.6788 - accuracy: 0.6000


# Evaluation 

* evaluate test on batch
* predict/predict_classes/predict_proba(only predict for generator etc)

In [51]:
model.evaluate(
            data,
            labels,
            batch_size=32,
            verbose=1,
            sample_weight=None)

32/32 [==============================] - 0s 544us/step - loss: 0.6638 - accuracy: 0.6010


[0.6638249754905701, 0.6010000109672546]

In [52]:
model.predict(
            data,
            batch_size=32,
            verbose=1)

32/32 [==============================] - 0s 373us/step


array([[0.58177596],
       [0.51481676],
       [0.48363435],
       [0.37324744],
       [0.5909763 ],
       [0.5085412 ],
       [0.5756633 ],
       [0.5098746 ],
       [0.43131375],
       [0.58133817],
       [0.5892435 ],
       [0.54077   ],
       [0.5013192 ],
       [0.5410947 ],
       [0.62009776],
       [0.34385467],
       [0.51875365],
       [0.5697975 ],
       [0.47216827],
       [0.6092778 ],
       [0.41083294],
       [0.58048546],
       [0.5323728 ],
       [0.5453252 ],
       [0.48651725],
       [0.55320704],
       [0.6096177 ],
       [0.5063046 ],
       [0.5143441 ],
       [0.51943004],
       [0.5602287 ],
       [0.5128446 ],
       [0.56864613],
       [0.5354724 ],
       [0.5388147 ],
       [0.54790336],
       [0.53065485],
       [0.44630828],
       [0.5328061 ],
       [0.65760213],
       [0.46917966],
       [0.45668143],
       [0.5905872 ],
       [0.45381984],
       [0.5425263 ],
       [0.60115963],
       [0.4705356 ],
       [0.644

In [53]:
model.predict_classes(
            data,
            batch_size=32,
            verbose=1)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
32/32 [==============================] - 0s 415us/step


array([[1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [55]:
model.predict_proba(
            data,
            batch_size=32,
            verbose=1)

Instructions for updating:
Please use `model.predict()` instead.
32/32 [==============================] - 0s 632us/step


array([[0.58177596],
       [0.51481676],
       [0.48363435],
       [0.37324744],
       [0.5909763 ],
       [0.5085412 ],
       [0.5756633 ],
       [0.5098746 ],
       [0.43131375],
       [0.58133817],
       [0.5892435 ],
       [0.54077   ],
       [0.5013192 ],
       [0.5410947 ],
       [0.62009776],
       [0.34385467],
       [0.51875365],
       [0.5697975 ],
       [0.47216827],
       [0.6092778 ],
       [0.41083294],
       [0.58048546],
       [0.5323728 ],
       [0.5453252 ],
       [0.48651725],
       [0.55320704],
       [0.6096177 ],
       [0.5063046 ],
       [0.5143441 ],
       [0.51943004],
       [0.5602287 ],
       [0.5128446 ],
       [0.56864613],
       [0.5354724 ],
       [0.5388147 ],
       [0.54790336],
       [0.53065485],
       [0.44630828],
       [0.5328061 ],
       [0.65760213],
       [0.46917966],
       [0.45668143],
       [0.5905872 ],
       [0.45381984],
       [0.5425263 ],
       [0.60115963],
       [0.4705356 ],
       [0.644